apiVersion: security.istio.io/v1beta1
kind: AuthenticationPolicy
metadata:
  annotations:
    role: edit
    user: armando@nioyatech.com # replace with the email of the user from your Active Directory case sensitive
  name: user-armando-nioyatech-com-clusterrole-edit
  namespace: machinelearning # replace with the namespace/profile name that you are adding contributors to
spec:
  action: ALLOW
  rules:
  - when:
    - key: request.headers[kubeflow-userid] # for GCP, use x-goog-authenticated-user-email instead of kubeflow-userid for authentication purpose
      values:
      - accounts.google.com:armando@nioyatech.com   # replace with the email of the user from your Active Directory case sensitive