apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    # Email address used for ACME registration
    email: armando@nioyatech.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: kf-nioyatechai-com-tls
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik