apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
  namespace: kubeflow
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: kubeflow
spec:
  ingressClassName: istio
  rules:
  - host: "*"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: centraldashboard
            port:
              number: 80