apiVersion: v1
kind: Service
metadata:
  labels:
    generic-service: generic-data-api
  name: generic-data-api-service
  namespace: kube_name
  annotations:
    app.gitlab.com/app: ci-path-slug
    app.gitlab.com/env: ci-env-slug
#spec:
  #type: NodePort
  #ports:
    #- name: http
      #port: 8080
      #targetPort: 8080
      #nodePort: 30033
  #selector:
    #generic-service: generic-data-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    generic-service: generic-data-api

